language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI은 GLIBC 2.27 이하 사용 → Nokogiri가 GLIBC 실행 시도하다가 에러 발생 → v1을 사용하게 함으로써 Nokogiri 사용 안하게 하기
before_install:
  - gem uninstall dpl --all --executables || true
  - gem install dpl -v 1.10.16 --no-document

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip 에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 전체 압축
  - mv before-deploy/before-deploy.zip deploy/springbase.zip # deploy로 zip 파일 이동

deploy:
  - provider: s3
    edge: false
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springbase-springboot-build
    region: ap-southeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 에 설정된 값
    bucket: springbase-springboot-build # S3 버킷
    key: springbase.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springbase # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: springbase-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wkc1002@naver.com
    on_success: always
    on_failure: always