language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI은 GLIBC 2.27 이하 사용 → Nokogiri가 GLIBC 실행 시도하다가 에러 발생 → v1을 사용하게 함으로써 Nokogiri 사용 안하게 하기
before_install:
  - gem uninstall dpl --all --executables || true
  - gem install dpl -v 1.10.16 --no-document

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springbase ./*
  - mkdir -p deploy
  - mv springbase.zip deploy/springbase.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springbase-springboot-build
    region: ap-southeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wkc1002@naver.com
    on_success: always
    on_failure: always